name: Microsoft.JavaScript.LibNode

on:
  push:
    branches:
    - main
    - develop
  pull_request:
    branches:
    - main
    - develop

jobs:
  build-libnode:
    strategy:
      fail-fast: false
      matrix:
        rid:
        - win-x64
        - linux-x64
        - osx-x64
        - osx-arm64
    name: Build libnode (${{ matrix.rid }})
    runs-on: ${{ fromJSON('{"win-x86":["windows-2022"],"win-x64":["windows-2022"],"linux-x64":["ubuntu-22.04"],"osx-x64":["macos-13"],"osx-arm64":["macos-14"]}')[matrix.rid] }}
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
    - name: Build libnode (Windows)
      if: runner.os == 'Windows'
      run: .\vcbuild dll
    - name: Build libnode (Unix)
      if: runner.os != 'Windows'
      run: .\configure --shared
