name: Microsoft.JavaScript.LibNode

on:
  workflow_dispatch:
  push:
    branches:
    - main
    - develop
  pull_request:
    branches:
    - main
    - develop

jobs:
  build-libnode:
    strategy:
      fail-fast: false
      matrix:
        rid:
        - win-x64
        - linux-x64
        - osx-x64
        - osx-arm64
    name: Build libnode (${{ matrix.rid }})
    runs-on: ${{ fromJSON('{"win-x86":["windows-2022"],"win-x64":["windows-2022"],"linux-x64":["ubuntu-22.04"],"osx-x64":["macos-13"],"osx-arm64":["macos-14"]}')[matrix.rid] }}
    steps:
    - name: Checkout Source
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 0
    - name: Install winget-install
      if: runner.os == 'Windows'
      shell: pwsh
      run: Install-Script winget-install
    - name: Install winget
      if: runner.os == 'Windows'
      shell: pwsh
      run: winget-install
    - name: Configure
      if: runner.os == 'Windows'
      shell: pwsh
      run: winget configure -f .\.configurations\configuration.dsc.yaml --disable-interactivity
      working-directory: .\ext\node
    - name: Build
      if: runner.os == 'Windows'
      run: .\vcbuild dll
      working-directory: .\ext\node
    - name: Build
      if: runner.os != 'Windows'
      run: ./configure --shared && make -j4
      working-directory: ./ext/node
    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: libnode--${{ matrix.rid }}
        path: ./ext/node/Release